version: "3.6"

services:

  web:
    image: nginx:alpine
    container_name: clj-test-nginx
    volumes:
      - ./env/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/log/nginx
    ports:
      - 8080:80
      - 3449:3449    
    depends_on:
      - back-api
      - front-app
      - adminer
    networks:
      clj-test:

  back-api:
    image: clojure:lein-2.8.1
    container_name: clj-test-back-api
    working_dir: /usr/src/app
    volumes:
        - ./back/api:/usr/src/app
    command: "lein ring server-headless"
    networks:
      clj-test:

  front-app:
    image: clojure:lein-2.8.1
    container_name: clj-test-front-app
    working_dir: /usr/src/app
    volumes:
        - ./front:/usr/src/app
    command: "lein figwheel"
    networks:
      clj-test:

  db:
    image: postgres:12-alpine
    container_name: clj-test-postgres
    environment:
      POSTGRES_USER: dev 
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
    ports:                 
      - 5432:5432          
    volumes:               
      - db-data:/var/lib/postgresql/data
      - ./log/postgres:/log/postgresql
      - ./env/docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    networks:
      clj-test:

  adminer:   
    image: adminer         
    container_name: clj-test-adminer  
    depends_on:
      - db
    networks:
      clj-test:

networks:
    clj-test:

volumes:
    db-data:

